GET http://localhost:3002/api/candies  
### Display all candy in DB
GET http://localhost:3002/api 
### Check app.js connection


POST http://localhost:3002/api/users/signup 
content-type: application/json

{
    "username": "logintest2",
    "password": "youwillneverguess2"
}
### Sign up user
POST http://localhost:3002/api/users/login 
content-type: application/json

{
    "username": "logintest2",
    "password": "youwillneverguess2"
}
### Log in user
POST http://localhost:3002/api/candies
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2ludGVzdDIiLCJ1c2VyaWQiOiI2NTI0OWEwNzY1MGM0ZWE3ZTY1MzIzY2MiLCJpYXQiOjE2OTY4OTc3NjYsImV4cCI6MTY5NjkwMTM2Nn0.mOPeDO8rPU1j_tXIHsxbevb7xxk2lC-qhW2Nken3CBo

{
    "id": "3",
    "name": "Jelly babies"
}
### Add candy and ID with Bearer from login
DELETE http://localhost:3002/api/candies/65249af3ffdf7bb5bc7b9760 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2ludGVzdDIiLCJ1c2VyaWQiOiI2NTI0OTlhOTYxZDlhNjNhMWMwMWJlNjAiLCJpYXQiOjE2OTY4OTc1NDYsImV4cCI6MTY5NjkwMTE0Nn0.vwuH8OyX9zmjPH-N5su-CiICY0FyLQK8pjrZZOZjYvM
### Delete candy or user by ID with Bearer from login